# Generated by Django 4.1.5 on 2023-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasolinerias',
            fields=[
                ('id_gasolineria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ubicacion', models.TextField(verbose_name='Ubicación')),
            ],
        ),
    ]
