# Generated by Django 4.1.5 on 2023-04-04 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0002_precios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuarios',
            fields=[
                ('id_tipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('fk_id_tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.tipo_usuarios')),
            ],
        ),
    ]
