# Generated by Django 4.1.5 on 2023-04-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0003_tipo_usuarios_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolineriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_gasolineria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.gasolinerias')),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolina.usuarios')),
            ],
        ),
    ]
