# Generated by Django 4.1.5 on 2023-04-06 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0004_gasolineriausuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_usuarios',
            new_name='TipoUsuarios',
        ),
        migrations.AddField(
            model_name='precios',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización'),
            preserve_default=False,
        ),
    ]
