# Generated by Django 4.1.5 on 2023-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0005_rename_tipo_usuarios_tipousuarios_precios_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='precio',
            field=models.FloatField(verbose_name='Precio Gasolina'),
        ),
    ]
