# Generated by Django 4.1.5 on 2023-04-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolina', '0006_alter_precios_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='precios',
            name='tipo_gasolina',
        ),
        migrations.AddField(
            model_name='precios',
            name='diesel',
            field=models.FloatField(default=0, verbose_name='Diesel'),
        ),
        migrations.AddField(
            model_name='precios',
            name='magna',
            field=models.FloatField(default=0, verbose_name='Magna'),
        ),
        migrations.AddField(
            model_name='precios',
            name='premium',
            field=models.FloatField(default=0, verbose_name='Premium'),
        ),
    ]
